name: Publish library packages

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "The package name to publish"
        required: true
        default: "@simplycubed/webflow-utils"
jobs:
  publish_if_newer_version:
    runs-on: ubuntu-latest
    name: publish_if_newer_version
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: NPM install
        run: npm install
      - name: Publish Webflow Utils
        if:
          ${{ github.event.inputs.package_name == '@simplycubed/webflow-utils'}}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_WEBFLOW_UTILS }}
        run: |
          cd webflow-utils
          ${{ github.workspace }}/.github/workflows/scripts/npm_publish.sh
